{% set name = "appimage-updater-bridge" %}
{% set version = "2.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/antony-jr/AppImageUpdaterBridge/archive/v{{ version }}.tar.gz
  sha256: 55b20b1da947aaaa11e7b4565ecd761dde0369bba548c25a740321e671f50068


build:
  number: 2
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - python ==3.10
    - cmake
    - ninja
  host:
    - qt-main
  run:
    - qt-main

test:
  files:
    - test.py
  requires:
    - python ==3.10
    - pyside2
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  commands:
    - test -f ${PREFIX}/plugins/libQAppImageUpdate.so
    - QT_DEBUG_PLUGINS=1 python test.py

about:
  home: https://github.com/antony-jr/AppImageUpdaterBridge
  license: BSD-3-Clause
  license_file: LICENSE
  summary: AppImage Updater Bridge is a delta updater based on the zsync algorithm
  description: |
    AppImage Updater Bridge is a delta updater based on the zsync algorithm for the AppImage format , 
    Using this library you can delta update any AppImage file , That is , 
    Only download the binary data which you need to get the latest version , Therefore saving your time and internet.
  doc_url: https://github.com/antony-jr/AppImageUpdaterBridge
  dev_url: https://github.com/antony-jr/AppImageUpdaterBridge

extra:
  recipe-maintainers:
    - looooo
    - antony-jr
